### ISSUE TITLE
Development environment broken

### ISSUE THREAD

**Issue by aadcg** [sigprof/guix-qmk#2]
A [recent Guix commit](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=d35bc00cc1c27043f212762786d89a94c16de3fe) deleted `avr-toolchain` as a package.

**Comment by sigprof** [comment]
Should be fixed by 37d6612369eb29b78471e9199465c274de157d2c (and 5a7d6022447a8642ce9e4d29c7501ae06e951ebb was then needed to work around the breakage of `(make-newlib-nano-arm-none-eabi-7-2018-q2-update)` introduced by those Guix changes).

**Comment by aadcg** [comment]
Thanks for looking into it!
